---
title: "StatProg2 - A statistical programming exercise on student AI behaviour"
author:
  - "Paul Gustav Hoffmann"
date: today
---

## Introduction

Our world has changed a lot since the rise of generative AI
including our everyday life, economy and how we learn things.
Questions arise about how students are affected by these changes
and how they can benefit most from generative AI for their academic success.  

To give insights into this matter we will try to answer the following questions
given the synthetic dataset "Impact of Ai on Students" by laveshjadon:

*1. In which majors is the GPA most affected by heavier AI Usage?*  
*2. How can AI be used for the best GPA score?*

## Data

The synthetic dataset "Impact of Ai on Students" by laveshjadon is about the generative AI usage of students and its effects on them.
It features 50000 simulated students with 16 features.
They capture various key information of the students (e.g. their major, study year & GPA score),
but also how they use generative AI (e.g. which tools they use, which use case they have & their prompting skills).

## Results

First, we observed that heavy AI usage seems to have a damaging effect on the grade
when using it for more than half of the learning time and this is independent of the majors. 
Some outliers suffer from this with an extraordinarily worse GPA after the end of their current semester.  

Secondly, we have created a model which is able to tell a student how they should use AI for their best GPA. 
After trying out a train test split and analyzing the feature importance we were confident with the model's quality. 
But by trying out every possible input parameter combination, we found out that 
every suggestion is in fact pretty much independent of the input parameters (which describe the student's situation). 
So given the dataset there is a single suggestion for every student coming from the variables which are not noise in the model:  
`Study smarter, not harder, while using AI as little as possible.`  
`But if you use it, ensure it's rather for arbitrary work like debugging and not for straight up solving your exercises.`

## Discussion

Given the dataset is synthetic, the observations and conclusions from this research
might be statistically correct, but the dataset (even though realistic) is prone to have
biases which might make these findings in fact incorrect. Caution is a must.  

Keep in mind that the first observation comes from the GPA change over one semester, 
so heavy AI usage might as well only be a short-term disadvantage or might even increase the GPA 
in the long term. This data alone cannot answer that.  

The model is bound to have some biases, given synthetic data cannot be a perfect 
representation of the real world, but I still believe the overall message of the analysis is sensible.

