---
title: "Project Proposal"
author:
  - "Group Member 1"
  - "Group Member 2"
  - "Group Member 3"
date: today
---

## Dataset

<!-- Describe the dataset: source, licence, dimensions, key variables. -->
The source of the data is:  
https://www.kaggle.com/datasets/laveshjadon/ai-impact-on-students?select=ai_student_impact_dataset+%281%29.csv  

The data is licenced under CC0 1.0 Universal:  
(https://creativecommons.org/publicdomain/zero/1.0/)

*Content:*  
The dataset "Impact of Ai on Students" is about the generative AI usage of students and its effects on them.

There are 50000 rows representing 50000 observed students. 
Also 16 observed features are listed in its 16 columns.  
They capture various key information of the students
(e.g. their major, study year & GPA score),
but also how they use generative AI
(e.g. which tools they use, which usecase they have & their prompting skills).

## Research Questions

*1. In which majors is the GPA most affected by heavier AI Usage?*  
*2. Does the GPA correlate with paid subscriptions & tool diversity?*

The audience for this analysis are students and
the goal is to help them understand in which way AI usage is beneficial to the grade.  
The overall message is more important then the details for this scenario,
so simple visualizations like graphs without clutter should work best.

## Initial EDA

```{r}
#| label: load-data
library(tidyverse)
library(here)

# data <- read_csv(here("data", "raw", "data.csv"))
```

<!-- Add 2–3 exploratory plots and a brief commentary on what you observe. -->

## Analysis Plan

<!-- Outline the methods you plan to use to answer your research questions. -->
